version: 2.1

executors:
  amd64:
    machine:
      image: ubuntu-2204:2022.10.2
      docker_layer_caching: true
    resource_class: medium
    environment:
      DOCKER_BUILDKIT: 1
  arm64:
    machine:
      image: ubuntu-2204:2022.10.2
      docker_layer_caching: true
    resource_class: arm.medium
    environment:
      DOCKER_BUILDKIT: 1
  docker: &docker-executor
    docker:
      - image: ruby:latest

commands:
  install_docker_client:
    description: "Install Docker client"
    steps:
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="20.10.22"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
  checkout_ruby_master:
    description: "Checkout Ruby master"
    steps:
      - run:
          command: |
            if test -f tmp/ruby/configure.ac; then
              cd tmp/ruby
              git pull --rebase
            else
              mkdir -p tmp
              git clone https://github.com/ruby/ruby.git tmp/ruby
            fi
  build_image:
    description: "Build Docker image"
    parameters:
      ruby_version:
        type: string
        default: "master"
      nightly:
        type: boolean
        default: false
      image_version_suffix:
        type: string
        default: ''
      ubuntu_version:
        type: string
        default: "focal"
      tag_suffix:
        type: string
        default: ""
      target:
        type: string
        default: "ruby"
      latest_tag:
        type: string
        default: "false"
    steps:
      - run:
          name: Build docker image
          command: |
            rake docker:build ruby_version=<< parameters.ruby_version >> \
                              ubuntu_version=<< parameters.ubuntu_version >> \
                              image_version_suffix=<< parameters.image_version_suffix >> \
                              <<# parameters.nightly >>nightly=yes<</ parameters.nightly >> \
                              tag_suffix=<< parameters.tag_suffix >> \
                              target=<< parameters.target >> \
                              latest_tag=<< parameters.latest_tag >>
  push_image:
    description: "Push Docker image to DockerHub"
    steps:
      - run:
          name: Push docker image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push rubylang/ruby
  push_image_by_tag:
    description: "Push specific tags of Docker image to DockerHub"
    parameters:
      push_tags:
        type: string
    steps:
      - run:
          name: Push docker image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            push_tags="<<parameters.push_tags>>"
            for tag in $push_tags; do
              docker push rubylang/ruby:$tag
            done
  push_image_by_tag_ghcr:
    description: "Push specific tags of Docker image to GHCR"
    parameters:
      push_tags:
        type: string
    steps:
      - run:
          name: Push docker image to GHCR
          command: |
            echo $GHCR_ACCESS_TOKEN | docker login ghcr.io -u $GITHUB_USER --password-stdin
            push_tags="<<parameters.push_tags>>"
            for tag in $push_tags; do
              docker tag rubylang/ruby:$tag ghcr.io/ruby/ruby:$tag
              docker push ghcr.io/ruby/ruby:$tag
            end

jobs:
  build:
    parameters:
      nightly:
        type: boolean
        default: false
      push:
        type: boolean
        default: false
      ubuntu_version:
        type: string
        default: "focal"
      ruby_version:
        type: string
        default: "master"
      executor:
        type: executor
      tag_suffix:
        type: string
        default: ""
      push_tags:
        type: string
        default: ""
    executor: << parameters.executor >>
    working_directory: ~/repo
    steps:
      - checkout
      - when:
          condition: # if tag is not set, assume it's not multiarch
            equal: ["docker", << parameters.executor >>]
          steps:
            - setup_remote_docker:
                version: 20.10.14
            - install_docker_client
      - when:
          condition:
            equal: ["master", << parameters.ruby_version >>]
          steps:
            - checkout_ruby_master
      - build_image:
          ruby_version: << parameters.ruby_version >>
          nightly: << parameters.nightly >>
          ubuntu_version: << parameters.ubuntu_version >>
          tag_suffix: << parameters.tag_suffix >>
          latest_tag: "true"
      - build_image:
          ruby_version: << parameters.ruby_version >>
          nightly: << parameters.nightly >>
          ubuntu_version: << parameters.ubuntu_version >>
          image_version_suffix: -dev
          tag_suffix: << parameters.tag_suffix >>
          target: "development"
      - when:
          condition: << parameters.push >>
          steps:
            - push_image
      - when:
          condition: << parameters.push_tags >>
          steps:
            - push_image_by_tag:
                push_tags: << parameters.push_tags >>

  build_master_debug:
    parameters:
      nightly:
        type: boolean
        default: false
      push:
        type: boolean
        default: false
      ubuntu_version:
        type: string
        default: "focal"
    docker:
      - image: ruby:latest
    working_directory: ~/repo
    environment:
      cppflags: -DRUBY_DEBUG=1
      optflags: -O3 -fno-inline
    steps:
      - checkout
      - setup_remote_docker
      - install_docker_client
      - checkout_ruby_master
      - build_image:
          ruby_version: "master"
          nightly: << parameters.nightly >>
          ubuntu_version: << parameters.ubuntu_version >>
          image_version_suffix: -debug
          target: "develpment"
      - when:
          condition: <<parameters.push>>
          steps:
            - push_image

  deploy_multiarch:
    parameters:
      ruby_version:
        type: string
      ubuntu_version:
        type: string
      executor:
        type: executor
      registry_name:
        type: string
        default: rubylang
    executor: << parameters.executor >>
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Create manifest for DockerHub"
          command: |
            rake docker:manifest:create \
                 registry_name="<<parameters.registry_name>>" \
                 ruby_version="<<parameters.ruby_version>>" \
                 ubuntu_version="<<parameters.ubuntu_version>>" \
                 architectures="amd64 arm64" \
                 manifest_suffix=${CIRCLE_SHA1} \
                 latest_tag=true
            rake docker:manifest:create \
                 registry_name="<<parameters.registry_name>>" \
                 ruby_version="<<parameters.ruby_version>>" \
                 ubuntu_version="<<parameters.ubuntu_version>>" \
                 architectures="amd64 arm64" \
                 image_version_suffix=-dev \
                 manifest_suffix=${CIRCLE_SHA1}
      - run:
          name: "Push manifest to DockerHub"
          command: |
            case x"<<parameters.registry_name>>" in
              xghcr.io/ruby)
                DOCKER_USER=$GITHUB_USER
                DOCKER_PASS=$GHCR_ACCESS_TOKEN
                ;;
              xrubylang)
                ;;
              *)
                echo "ERROR: Unknown registry_name parameter: $registry_name" >&2
                exit 1
                ;;
            esac

            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            rake docker:manifest:push \
                 registry_name="<<parameters.registry_name>>" \
                 ruby_version="<<parameters.ruby_version>>" \
                 ubuntu_version="<<parameters.ubuntu_version>>" \
                 latest_tag=true
            rake docker:manifest:push \
                 registry_name="<<parameters.registry_name>>" \
                 ruby_version="<<parameters.ruby_version>>" \
                 ubuntu_version="<<parameters.ubuntu_version>>" \
                 image_version_suffix=-dev

parameters:
  ruby_version:
    type: string
    description: '"master" or version nunmber ("3.1.2")'
    default: ""
  ubuntu_version:
    type: string
    default: "focal"

workflows:
  version: 2

  nightly:
    triggers:
      - schedule:
          cron: "0 17 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          nightly: true
          push: true
          ubuntu_version: "focal"
          executor: docker
      - build:
          nightly: true
          push: true
          ubuntu_version: "bionic"
          executor: docker
      - build_master_debug:
          nightly: true
          push: true

  # Build amd64/arm64 multiarch docker image as "focal-3.1.2-multi"
  # only triggered when pipeline is kicked over API
  build_multiarch:
    when:
      and:
        - not:
            equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        - << pipeline.parameters.ruby_version >>
    jobs:
      - build:
          name: "build_amd64"
          ruby_version: << pipeline.parameters.ruby_version >>
          ubuntu_version: << pipeline.parameters.ubuntu_version >>
          executor: "amd64"
          tag_suffix: -amd64-${CIRCLE_SHA1}
          push_tags: |
            << pipeline.parameters.ruby_version >>-<< pipeline.parameters.ubuntu_version >>-amd64-${CIRCLE_SHA1}
            << pipeline.parameters.ruby_version >>-dev-<< pipeline.parameters.ubuntu_version >>-amd64-${CIRCLE_SHA1}
      - build:
          name: "build_arm64"
          ruby_version: << pipeline.parameters.ruby_version >>
          ubuntu_version: << pipeline.parameters.ubuntu_version >>
          executor: "arm64"
          tag_suffix: -arm64-${CIRCLE_SHA1}
          push_tags: |
            << pipeline.parameters.ruby_version >>-<< pipeline.parameters.ubuntu_version >>-arm64-${CIRCLE_SHA1}
            << pipeline.parameters.ruby_version >>-dev-<< pipeline.parameters.ubuntu_version >>-arm64-${CIRCLE_SHA1}
      - deploy_multiarch:
          name: "deploy_multiarch_dockerhub"
          requires:
            - build_amd64
            - build_arm64
          executor: "amd64"
          registry_name: rubylang
          ruby_version: << pipeline.parameters.ruby_version >>
          ubuntu_version: << pipeline.parameters.ubuntu_version >>
      - deploy_multiarch:
          name: "deploy_multiarch_ghcr"
          requires:
            - build_amd64
            - build_arm64
          executor: "amd64"
          registry_name: ghcr.io/ruby
          ruby_version: << pipeline.parameters.ruby_version >>
          ubuntu_version: << pipeline.parameters.ubuntu_version >>
