name: build_image
inputs:
  ruby_version:
    required: false
    default: master
  nightly:
    required: false
    default: false
  image_version_suffix:
    required: false
    default: ''
  ubuntu_version:
    required: false
    default: focal
  tag_suffix:
    required: false
    default: ''
  target:
    required: false
    default: ruby
  latest_tag:
    required: false
    default: 'false'
runs:
  using: composite
  steps:
  - name: Build docker image
    run: |-
      rake docker:build ruby_version=${{ inputs.ruby_version }} \
                        ubuntu_version=${{ inputs.ubuntu_version }} \
                        image_version_suffix=${{ inputs.image_version_suffix }} \
                        ${{ inputs.nightly }}nightly=yes${{ inputs.nightly }} \
                        tag_suffix=${{ inputs.tag_suffix }} \
                        target=${{ inputs.target }} \
                        latest_tag=${{ inputs.latest_tag }}
    shell: bash
  - name: List images
    run: docker images
    shell: bash