name: Build Docker image

on:
  workflow_dispatch:
    inputs:
      RUBY_VERSION:
        description: The version of Ruby to be build
        required: true
        default: master
      ARCH:
        description: Which architecture amd64 or arm64 do you want to build? (The default is amd64)
        required: false
        default: amd64

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          rake docker:build arch=${{ github.event.inputs.arch }} ruby_version=${{ github.event.inputs.RUBY_VERSION }}

      - name: Check image
        run: |
          docker images
          docker run rubylang/ruby:${{ github.event.inputs.RUBY_VERSION }}-bionic ruby -v

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push images to DockerHub
        run: docker push rubylang/ruby

      - name: Renaming images
        run: |
          docker images rubylang/ruby | grep ^rubylang/ruby | ruby <<EOS
            while x = gets
              name, tag, = x.strip.split(",")
              name = name.split("/")[1]
              system "docker", "tag", "rubylang/#{tag}", "ruby-docker-images/#{tag}"
            end
          EOS

      - name: Login GitHub Package Registory
        run: docker login docker.pkg.github.com -u owner -p ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GitHub Package Registory
        run: docker push docker.pkg.github.com/${{ github.repository }}/ruby
