name: Check index.txt

on:
  # See https://github.com/ruby/actions/blob/master/.github/workflows/update_index.yml#L5
  # schedule:
  #- cron: '11 2-23/3 * * *'
  push:
    branches:
    - check-index-test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install
      run: |
        set -x
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y ruby
    - name: Clone the repository
      run: |
        git clone --depth=1 --branch=check-index-test --single-branch https://github.com/ruby/ruby-docker-images .
    - name: Download index.txt
      run: |
        curl -O http://cache.ruby-lang.org/pub/ruby/index.txt
        ls
        cat index.txt

    - name: Check index.txt
      run: |
