name: ruby/ruby-docker-images/nightly

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  GHCR_USER: ${{ secrets.GHCR_USER }}
  GHCR_ACCESS_TOKEN: ${{ secrets.GHCR_ACCESS_TOKEN }}

jobs:
  build:
    strategy:
      matrix:
        os: [jammy, focal]
        debug: ['', '-debug']
        dev: ['', '-dev']

    runs-on: ubuntu-latest

    env:
      nightly: true
      push: true
      ubuntu_version: ${{ matrix.os }}
      ruby_version: master
      image_version_suffix: ${{ matrix.debug }}
      tag_suffix: ''
      push_tags: ''
      dev_suffix: ${{ matrix.dev }}
      optflags: ''
      cppflags: ''
      debugflags: ''

    steps:
    - uses: actions/checkout@v4.1.0

    - run: |
        if [ "${{ env.dev_suffix }}" = "-dev" ]; then
          echo "target=development" >> $GITHUB_ENV
        else
          echo "target=ruby" >> $GITHUB_ENV
        fi

    - uses: "./.github/actions/build_image"
      with:
        ruby_version: "${{ env.ruby_version }}"
        nightly: "${{ env.nightly }}"
        image_version_suffix: "${{ env.image_version_suffix }}${{ env.dev_suffix }}"
        ubuntu_version: "${{ env.ubuntu_version }}"
        tag_suffix: "${{ env.tag_suffix }}"
        target: ${{ env.target }}

    - uses: "./.github/actions/push_image"
      if: "${{ env.push }}"
      with:
        ruby_version: "${{ env.ruby_version }}"
        nightly: "${{ env.nightly }}"
        image_version_suffix: "${{ env.image_version_suffix }}${{ env.dev_suffix }}"
        ubuntu_version: "${{ env.ubuntu_version }}"
        tag_suffix: "${{ env.tag_suffix }}"

    - uses: "./.github/actions/push_image"
      if: "${{ env.push }}"
      with:
        registry_name: 'ghcr.io/ruby'
        ruby_version: "${{ env.ruby_version }}"
        nightly: "${{ env.nightly }}"
        image_version_suffix: "${{ env.image_version_suffix }}${{ env.dev_suffix }}"
        ubuntu_version: "${{ env.ubuntu_version }}"
        tag_suffix: "${{ env.tag_suffix }}"

    - uses: "./.github/actions/push_image_by_tag"
      if: "${{ env.push_tags }}"
      with:
        push_tags: "${{ env.push_tags }}"
