name: ruby/ruby-docker-images/nightly

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  GHCR_USER: ${{ secrets.GHCR_USER }}
  GHCR_ACCESS_TOKEN: ${{ secrets.GHCR_ACCESS_TOKEN }}

jobs:
  build:
    strategy:
      matrix:
        os: [jammy, focal]
        debug: ['', '-debug']
        dev: ['', '-dev']

    runs-on: ubuntu-latest

    env:
      nightly: true
      push: true
      ubuntu_version: ${{ matrix.os }}
      ruby_version: master
      image_version_suffix: ${{ matrix.debug }}
      tag_suffix: ''
      push_tags: ''
      dev_suffix: ${{ matrix.dev }}
      optflags: ''
      cppflags: ''
      debugflags: ''

    steps:
    - uses: actions/checkout@v4.1.0

    - run: |
        if [ "${{ env.dev_suffix }}" = "-dev" ]; then
          echo "target=development" >> $GITHUB_ENV
        else
          echo "target=ruby" >> $GITHUB_ENV
        fi

    - name: Build docker image
      run: |-
        rake docker:build ruby_version=${{ env.ruby_version }} \
                          ubuntu_version=${{ env.ubuntu_version }} \
                          image_version_suffix=${{ env.image_version_suffix }}${{ env.dev_suffix }} \
                          nightly=${{ env.nightly }} \
                          tag_suffix=${{ env.tag_suffix }} \
                          target=${{ env.target }} \
                          latest_tag=${{ env.latest_tag }} \
                          arch=linux/amd64
      shell: bash

    - name: List images
      run: docker images
      shell: bash

    - name: Push docker image to rubylang
      if: ${{ env.push }}
      run: |-
        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
        rake docker:push ruby_version=${{ env.ruby_version }} \
                         ubuntu_version=${{ env.ubuntu_version }} \
                         image_version_suffix=${{ env.image_version_suffix }}${{ env.dev_suffix }} \
                         nightly=${{ env.nightly }} \
                         tag_suffix=${{ env.tag_suffix }} \
                         latest_tag=false \
                         registry_name=rubylang
        shell: bash

    - name: Push docker image to ghcr.io/ruby
      if: ${{ env.push }}
      run: |-
        echo $GHCR_ACCESS_TOKEN | docker login ghcr.io -u $GHCR_USER --password-stdin
        rake docker:push ruby_version=${{ env.ruby_version }} \
                         ubuntu_version=${{ env.ubuntu_version }} \
                         image_version_suffix=${{ env.image_version_suffix }}${{ env.dev_suffix }} \
                         nightly=${{ env.nightly }} \
                         tag_suffix=${{ env.tag_suffix }} \
                         latest_tag=false \
                         registry_name=ghcr.io/ruby
      shell: bash

    - uses: "./.github/actions/push_image_by_tag"
      if: "${{ env.push_tags }}"
      with:
        push_tags: "${{ env.push_tags }}"
